### ISSUE TITLE
Behavior with several suppliers

### ISSUE THREAD

**Issue by Trebia** [XiozZe/XioScript#62] opened 2016-03-27 21:28 UTC
Having the following setting:
- A factory
- Several suppliers identified for the same product.
- Selected 3x supply in XioScript
- It has not been tested any other combination (might also happen).

XioScript behaves the following:
- Provides a warning that there are no suppliers or too many.
- Sets the supply to 0 in any case.

How I would propose to behave:
- Provides the warning.
- Takes the supplier with higher purchase the previous turn and uses as the first option to match the required supply, while keeping the same value in the other suppliers.
- If the supplier with the highest purchase the previous turn is not able to meet the needs, XioScript should go to the second supplier with higher purchase the second turn and tries to match.
- In any case should not reduce to 0 the value unless 3x supply met.

**Comment by XiozZe** [comment] 2016-03-28 10:23
I might want to fully support several suppliers, if I take the time to do this. That warning I gave was just so that I wasn't obliged to script the possibility of having multiple suppliers. The problem lies in the "several suppliers identified for the same product": I have to figure out how to do that.

**Comment by Trebia** [comment] 2016-03-28 11:09
Um... I would divide in 2 steps the development:

- Avoid that supply request is set to 0 when there are several suppliers at the same time (looks more like a bug).
- Full support to several suppliers

**Comment by XiozZe** [comment] 2016-03-28 11:14
It's not a bug, it's intended: if you have two products, with the first product having two suppliers and the second none, the supply of the second product will be filled in the input of the second supplier of the first product. To prevent that, I set the supply to zero. But of course, I will get rid of that when I support several suppliers

**Comment by XiozZe** [comment] 2016-04-02 18:57
I'm sometimes randomly picking these problems up. I of course try to test any scenario a player could come with, but depends on my creativity on that moment.

**Comment by Trebia** [comment] 2016-04-02 22:59
:), man this script is terrific, is really changing the way I am playing the game.

**Comment by XiozZe** [comment] 2016-06-27 19:04
Multiple suppliers supported. An additional option row with "PQR", "Price" and "Quality" added, that determine on which factor it will sort (as in, pick the one with the lowest price first). Will put a warning when a good has no suppliers, or not enough suppliers to fulfill the required supply. Will be in the upcoming XS 12.1.0

**Closed by XiozZe** 2016-06-27 19:04 UTC
